MVCManukauTech/ViewModels/CheckoutViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCManukauTech.ViewModels
{
    // 11042019 NV Checkout viewmodel
    public class CheckoutViewModel
    {
        [Key]
        public int CheckoutId { get; set; }
        public string ShipName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public decimal Discount { get; set; }
        public decimal GrossTotal { get; set; }
        public decimal? GrandTotal { get; set; }
        public string ShipAddress { get; set; }
    }
}

MVCManukauTech/Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCManukauTech.Models.DB;
using MVCManukauTech.ViewModels;

namespace MVCManukauTech.Controllers
{
    public class OrderDetailsController : Controller
    {
        
        private readonly F191_NSS_ProjectContext _context;

        public OrderDetailsController(F191_NSS_ProjectContext context)
        {
            _context = context;
        }
        
        // 09042019 NV Create cart controller and views from JPC XSpy Project
        // or to simply view the cart
        // GET: OrderDetails/ShoppingCart
        public IActionResult ShoppingCart()
        {
            string SQLGetOrder = "";
            string SQLStartOrder = "";
            string SQLCart = "";
            string SQLBuy = "";
            string SQLUnitCostLookup = "";
            int rowsChanged = 0;
            // NV Changed to int
            int ProductId = Convert.ToInt32(Request.Query["ProductId"]);

            //SKH to check if there is already a membership product added to the cart
            if(checkCartForMembershipProduct(ProductId))
            {
                return Redirect("/Membership/MembershipAlreadyInCart");
            }

            else
            {
                //Have we created an order for this user yet?
            //If not then create a placeholder for a mostly empty order
            //Note that any Order in progress has an OrderStatusId of 0 or 1
            //We are not interested in Orders with higher status because they have already gone through checkout
            //2015-08-07 JPC Security improvement implementation of @p0
            //2019-03-19 JPC Change of table name from Orders to Order causes keyword clash 
            //  and therefore need to wrap Order in square brackets!
            SQLGetOrder = "SELECT * FROM [Order] WHERE SessionId = @p0 AND OrderStatusId <= 1;";

            //140825 JPC.  We may need 2 attempts at reading the order out of the database.
            //  Managing this as a for..loop with 2 loops.  If successful first time then break out.
            //  (Other opinion Rosemarie T - "this is a bit dodgy!")
            //150807 JPC Security improvement implementation of @p0
            var orders = _context.Order.FromSql(SQLGetOrder, HttpContext.Session.Id).ToList();
            for (int i = 0; i <= 1; i++)
            {
                //Do we have an order?
                if (orders.Count == 1)
                {
                    //we have an order, we can continue to the next step
                    break;
                }
                else if (i == 1)
                {
                    //failed on the second attempt
                    throw new Exception("ERROR with database table 'Order'.  This session fails to write a new order.");
                }
                else if (orders.Count > 1)
                {
                    //This would be a major error. In theory impossible but we need to be ready for any outcome
                    throw new Exception("ERROR with database table 'Order'.  This session is running more than one shopping cart.");
                }
                else
                {
                    //else we get an order started
                    //150807 JPC Security improvement implementation of @p0
                    SQLStartOrder = "INSERT INTO [Order](SessionId, OrderStatusId) VALUES(@p0, 0);";
                    rowsChanged = _context.Database.ExecuteSqlCommand(SQLStartOrder, HttpContext.Session.Id);
                    // a good result would be one row changed
                    if (rowsChanged != 1)
                    {
                        //Error handling code to go in here.  Poss return a view with error messages.
                        //Code from our old webforms version is -- 
                        throw new Exception("ERROR with database table 'Order'.");
                    }
                    //ready to try reading that order again
                    //150807 JPC Security improvement implementation of @p0, parameter Session.SessionID
                    orders = _context.Order.FromSql(SQLGetOrder, HttpContext.Session.Id).ToList();
                    //go round and test orders again
                }
            }

            //What is the OrderId
            int orderId = orders[0].OrderId;
            
            //150807 JPC Security improvement implementation of @p0
            //20180313 JPC temp drop parameter because of problems
            SQLCart = @"SELECT OrderDetail.OrderId AS OrderId, OrderDetail.LineNumber As LineNumber, OrderDetail.ProductId As ProductId,
                Product.ProductName As ProductName, Product.ImageFileName As ImageFileName,
                OrderDetail.Quantity As Quantity, OrderDetail.UnitPrice As UnitCost
                FROM OrderDetail INNER JOIN Product ON Product.ProductId = OrderDetail.ProductId
                WHERE OrderDetail.OrderId = @p0 ORDER BY OrderDetail.LineNumber;";
            // Note that this is an "view" query across 2 tables 
            // so we need to create a new VIEW MODEL class "OrderDetailsQueryForCart" to match up
            // See this under folder "ViewModels"
            //150807 JPC Security improvement implementation of @p0, parameter orderId
            var cart = _context.OrderDetailsQueryForCartViewModel.FromSql(SQLCart, orderId).ToList();

            //140903 JPC
            //What to do about a product for the case where the user clicked add to cart ..
            //IF the product is already in the cart THEN raise the quantity by one ELSE add it in

            int lineNumber = 0;
            int? quantity = 0;

            //140903 JPC cover case of user is only looking at the cart without adding any changes
            if (ProductId == 0)
            {
                //use lineNumber = -1 as a flag to skip the data writing in the following "if" block
                lineNumber = -1;
            }
            else
            {
                foreach (var item in cart)
                {
                    //NV changed here for int ProductID
                    if (item.ProductId == ProductId)
                    {
                        lineNumber = item.LineNumber;
                        quantity = item.Quantity;
                        break;
                    }
                }
            } //end if

            rowsChanged = 0;
            if (lineNumber > 0)
            {
                quantity += 1;
                //150807 JPC Security improvement implementation of @p0, @p1, @p2 - (was {0}, {1}, {2})
                SQLBuy = "UPDATE OrderDetail SET Quantity = @p0 WHERE OrderId = @p1 AND LineNumber = @p2 ";
                rowsChanged = _context.Database.ExecuteSqlCommand(SQLBuy, quantity, orderId, lineNumber);
            }
            else if (lineNumber == 0)
            {
                //writing a new line.  we need to know the unitcost
                //in real life work this could grow into a major method in a separate class involving special member discounts etc
                //here there is a choice between sending it in the querystring, or doing a new database lookup 
                //the querystring is easier but I am concerned about users being able to interfere with querystrings so I will go with the database

                //Safe bet is to stick to the SELECT * approach to match the existing generated classes.  
                //Can also call this the "go with the flow" method
                //150807 JPC Security improvement implementation of @p0
                SQLUnitCostLookup = "SELECT * FROM Product WHERE ProductId = @p0";
                var products = _context.Product.FromSql(SQLUnitCostLookup, ProductId).ToList();
                decimal unitCost = Convert.ToDecimal(products[0].UnitPrice);

                lineNumber = cart.Count + 1;
                //150807 JPC Security improvement implementation of @p0 etc
                SQLBuy = "INSERT INTO OrderDetail VALUES(@p0, @p1, @p2, @p3, @p4)";
                rowsChanged = _context.Database.ExecuteSqlCommand(SQLBuy, orderId, lineNumber, ProductId, 1, unitCost);
            }

            //If User has selected a product to add then Query is UPDATE or INSERT but they both run like this
            if (SQLBuy != "")
            {
                if (rowsChanged != 1)
                {
                    //Error handling code to go in here.  Poss return a view with error messages.
                    //Code from our old webforms version is -- 
                    throw new Exception("ERROR with database table 'Order'.");
                }

                //If we have changed the cart in the database, then we need to reload it here
                //140903 JPC note the syntax for working with a "View Model"
                //150807 JPC Security improvement implementation of @p0, parameter orderId
                cart = _context.OrderDetailsQueryForCartViewModel.FromSql(SQLCart, orderId).ToList();
            }

            //Give that Session object some work to do to wake it up and get it functional
            HttpContext.Session.SetInt32("OrderId", orderId);
            //20180312 JPC use ViewBag to get the orderId to the cart for display
            ViewBag.OrderId = orderId;
            return View(cart);
            }

            

        }
        

        [HttpPost]
        public string ShoppingCartUpdate(string Quantity, string LineNumber)
        {
            string SQLUpdateOrderDetails = "";
            int rowsChanged = 0;

            //140903 JPC check that Quantity and LineNumber are numeric. Non-numeric or decimal could indicate hacker mischief-making
            //20180312 JPC IsNumeric method is coded at the bottom of this class
            if (!IsNumeric(Quantity) || !IsNumeric(LineNumber)

MVCManukauTech/Views/Checkout/CheckoutResult.cshtml
@{
    ViewData["Title"] = "CheckoutResult";
}

<h1>Checkout Result</h1>

@* NV Suuccessful payment page with message and redirect to home page *@
<script>
    window.onload = (function () {
        swal("Successful Payment")
            .then(() => {                
                window.location.replace("/home");
            });
        
    })    
</script>

MVCManukauTech/Views/Checkout/Index.cshtml
@model MVCManukauTech.ViewModels.CheckoutViewModel

@{
    ViewData["Title"] = "Checkout";
}

<h1>Checkout</h1>


<script src="https://www.paypalobjects.com/api/checkout.js"></script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <h3>Shipping Details</h3>
    
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <label for="CustomerName" class="control-label col-md-2" style="display:inline">Name:</label>
            <div class="col-md-10">
                <input type="text" id="ShipName" name="ShipName" value="@Model.ShipName" style="display:inline" placeholder="required" autofocus required/>
            </div>
        </div>

        <div class="form-group">
            <label for="StreetAddress" class="control-label col-md-2" style="display:inline">Street Address:</label>
            <div class="col-md-10">
                <input type="text" id="StreetAddress" name="StreetAddress" value="@Model.StreetAddress" style="display:inline" placeholder="required" required/>
            </div>
        </div>

        <div class="form-group">
            <label for="City" class="control-label col-md-2" style="display:inline">City:</label>
            <div class="col-md-10">
                <input type="text" id="City" name="City" value="@Model.City" style="display:inline" placeholder="required" required/>
            </div>
        </div>

        <div class="form-group">
            <label for="PostCode" class="control-label col-md-2" style="display:inline">Postal Code:</label>
            <div class="col-md-10">
                <input type="text" id="PostCode" name="PostCode" value="@Model.PostalCode" style="display:inline" placeholder="required" required/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <b>Net Total : $@Math.Round(Model.GrossTotal, 2)</b>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <b>Discount : $@Math.Round(Model.Discount, 2)</b>
            </div>
        </div>
        @*NV Display grandtotal from controller*@
        <div class="form-group">
            <div class="col-md-10">
                <b>Grand total : $@ViewData["GrandTotal"]</b>

                <p></p>

                <div id="paypal-button"></div>
            </div>
        </div>


        <div>
            <a class="btn-warning"  asp-area="" asp-controller="OrderDetails" asp-action="ShoppingCart"> &lt; Return to Cart</a>
        </div>


    </div>
}

@*NV Paypal code *@
    <script>

        //document.addEventListener('contextmenu', event => event.preventDefault());
         //Paypal
    @*var grandTotal = @ViewBag.grandTotal;
        grandTotal = grandTotal.toFixed(2);*@


        paypal.Button.render({
            env: 'sandbox',
            client: {
                sandbox: 'AbNIc71vv_VWq2Rh2YfssLM2sq9lmIVzv9-1qOzssa8-_B-OJ5BfEj5G88YtI1sf6D7kBXxV_34p_16z'
            },
            commit: true, // Show a 'Pay Now' button

            style: {
                label: 'checkout',
                fundingicons: true, // optional
                branding: true, // optional
                size: 'responsive', // small | medium | large | responsive
                shape: 'pill',   // pill | rect
                color: 'gold'   // gold | blue | silve | black
            },

            payment: function (data, actions) {
                return actions.payment.create({
                    payment: {
                        transactions: [
                            {
                                amount: {
                                    total: Number(@ViewBag.GrandTotal).toFixed(2),
                                    currency: 'NZD'
                                }
                            }
                        ]
                    },
                    experience: {
                        input_fields: {
                            no_shipping: 1
                        }
                    }
                });
            },

            onAuthorize: function (data, actions) {
                /*
                 * Execute the payment here
                 */
                //location.replace("checkout/checkoutresult")

                //  https://stackoverflow.com/questions/45383047/how-to-get-the-transaction-id-using-paypal-express-checkout-integration-client?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

                return actions.payment.execute().then(function (payment) {

                    var paypalID = payment.transactions[0].related_resources[0].sale.id;

                    var xhttp = new XMLHttpRequest();
                    xhttp.open("GET", "/Checkout/PaypalResult?paypalID=" + paypalID, false);
                    xhttp.send();


                    var Res = xhttp.responseText;
                    if (Res == "Done") {
                        //sucessful payment
                        UpdateDatabase();                        
                        location.replace("Checkout/CheckoutResult");
                    }
                    else {                        
                        alert("Error");
                    }
                    
                });
            },

            onCancel: function (data, actions) {
                /*
                 * Buyer cancelled the payment
                 */
                location.replace("OrderDetails/ShoppingCart")
            },

            onError: function (err) {
                //NV In case of failed payment
                alert("Payment unsuccessful");
            }
    }, '#paypal-button');


    function UpdateDatabase() {
        var shipName = document.getElementById("ShipName").value;
        var shipAddress = document.getElementById("StreetAddress").value + ", " + document.getElementById("City").value
            + ", " + document.getElementById("PostCode").value;

        var xmlhttp = new XMLHttpRequest();
        xmlhttp.open("GET", "/Checkout/CheckoutUpdateDatabase?shipName=" + shipName + "&shipAddress=" + shipAddress
            + "&grossTotal=" + @Model.GrossTotal + "&discount=" + @Model.Discount + "&netTotal=" + @ViewData["GrandTotal"], false);
        xmlhttp.send();
        }
        

    </script>